coverage_service: cobertura_xml
xcodeproj: "My Project.xcodeproj"
scheme: "My Project"
configuration: Debug
source_directory: Sources
output_directory: xml_report
build_directory: "build"
binary_basename: "My App Debug"
ignore:
  - Resources/*