name: My Project
configs:
    Debug: debug
    Staging: release
    Release: release
options:
    createIntermediateGroups: true
    groupSortPosition: top
    generateEmptyDirectories: true
    indentWidth: 4
    tabWidth: 4
    bundleIdPrefix: "com.manhpham"
settings:
    PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    from: "5.5.0"
  RxMoya:
    url: https://github.com/Moya/Moya
    from: "15.0.0"
  RxSwift:
    url: https://github.com/ReactiveX/RxSwift
    from: "6.5.0"
  NSObject-Rx:
    url: https://github.com/RxSwiftCommunity/NSObject-Rx
    from: "5.1.1"
  RxSwiftExt:
    url: https://github.com/RxSwiftCommunity/RxSwiftExt
    from: "6.1.0"
  RxReachability:
    url: https://github.com/RxSwiftCommunity/RxReachability
    from: "1.2.1"
  PKHUD:
    url: https://github.com/pkluz/PKHUD
    from: "5.4.0"
  XCGLogger:
    url: https://github.com/DaveWoodCom/XCGLogger
    from: "7.0.0"
  Reusable:
    url: https://github.com/AliSoftware/Reusable
    from: "4.1.2"
  SwiftyUserDefaults:
    url: https://github.com/sunshinejr/SwiftyUserDefaults
    from: "5.3.0"
  Resolver:
    url: https://github.com/hmlongco/Resolver
    from: "1.5.0"
  MJRefresh:
    url: https://github.com/CoderMJLee/MJRefresh
    from: "3.7.5"
  Then:
    url: https://github.com/devxoul/Then
    from: "2.7.0"
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "8.12.1" 
targets:
  MyApp:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    sources: [Sources, Library]
    dependencies:
      - package: Alamofire
      - package: RxMoya
      - package: RxSwift
      - package: NSObject-Rx
      - package: RxSwiftExt
      - package: RxReachability
      - package: PKHUD
      - package: XCGLogger
      - package: Reusable
      - package: SwiftyUserDefaults
      - package: Resolver
      - package: MJRefresh
      - package: Then
      - package: Firebase
        product: FirebaseCrashlytics
    configFiles:
        Debug: Sources/Configs/BuildConfigurations/Debug.xcconfig
        Staging: Sources/Configs/BuildConfigurations/Staging.xcconfig
        Release: Sources/Configs/BuildConfigurations/Release.xcconfig
    settings:
        INFOPLIST_FILE: Sources/Resources/Info.plist
        SWIFT_VERSION: "5.0"
        SWIFT_OBJC_BRIDGING_HEADER: Sources/Resources/MyApp-Bridging-Header.h
        CODE_SIGN_STYLE: "Manual"
        UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        UILaunchStoryboardName: LaunchScreen
        EXCLUDED_ARCHS[sdk=iphonesimulator*]: "arm64"
        VALIDATE_WORKSPACE: YES
    preBuildScripts:
        - name: SwiftGen
          script: |
            if which swiftgen >/dev/null; then
              swiftgen
            else
              echo "warning: SwiftGen not installed, download it from https://github.com/SwiftGen/SwiftGen"
            fi
    postCompileScripts:
        - name: Swiftlint
          script: |
            if which swiftlint >/dev/null; then
              swiftlint
            else
              echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
            fi
        - name: GoogleServiceInfo
          script: |
            PATH_TO_GOOGLE_PLISTS="${PROJECT_DIR}/Sources/Configs/GoogleServices"
            case "${CONFIGURATION}" in
            "Debug" )
            cp -r "$PATH_TO_GOOGLE_PLISTS/GoogleService-Info-Debug.plist" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/GoogleService-Info.plist" ;;
            "Staging" )
            cp -r "$PATH_TO_GOOGLE_PLISTS/GoogleService-Info-Staging.plist" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/GoogleService-Info.plist" ;;
            "Release" )
            cp -r "$PATH_TO_GOOGLE_PLISTS/GoogleService-Info-Release.plist" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/GoogleService-Info.plist" ;;
            *)
            ;;
            esac
    postBuildScripts:
        - name: Crashlytics
          script: |
            ${BUILD_DIR%/Build/*}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run
          inputFiles:
            - $(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)
  MyAppTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/My App Debug.app/My App Debug
      LD_RUNPATH_SEARCH_PATHS: $(inherited) '@executable_path/Frameworks' '@loader_path/Frameworks' $(FRAMEWORK_SEARCH_PATHS)
      IPHONEOS_DEPLOYMENT_TARGET: 12.0
    sources: SourcesTests 
    dependencies:
      - target: MyApp  
schemes:
  My Project:
    build:
      targets:
        MyApp: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: MyAppTests
          parallelizable: false
          randomExecutionOrder: true
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Release