name: My Project
configs:
    Debug: debug
    Staging: release
    Release: release
options:
    createIntermediateGroups: true
    groupSortPosition: top
    generateEmptyDirectories: true
    indentWidth: 4
    tabWidth: 4
    bundleIdPrefix: "com.manhpham"
settings:
    PRODUCT_BUNDLE_IDENTIFIER: $(PRODUCT_BUNDLE_IDENTIFIER)
targets:
  MyApp:
    type: application
    platform: iOS
    deploymentTarget: "12.0"
    sources: [Sources, Library]
    dependencies:
      - framework: "Carthage/Build/Alamofire.xcframework"
      - framework: "Carthage/Build/Moya.xcframework"
      - framework: "Carthage/Build/RxSwift.xcframework"
      - framework: "Carthage/Build/RxCocoa.xcframework"
      - framework: "Carthage/Build/RxRelay.xcframework"
      - framework: "Carthage/Build/RxSwiftExt.xcframework"
      - framework: "Carthage/Build/NSObject_Rx.xcframework"
      - framework: "Carthage/Build/Resolver.xcframework"
      - framework: "Carthage/Build/Reusable.xcframework"
      - framework: "Carthage/Build/SwiftyUserDefaults.xcframework"
      - framework: "Carthage/Build/XCGLogger.xcframework"
      - framework: "Carthage/Build/ObjcExceptionBridging.xcframework"
      - framework: "Carthage/Build/Reachability.xcframework"
      - framework: "Carthage/Build/MJRefresh.xcframework"
      - framework: "Carthage/Build/PKHUD.xcframework"
      - framework: "Carthage/Build/RxMoya.xcframework"
      - framework: "Carthage/Build/FirebaseCrashlytics.xcframework"
      - framework: "Carthage/Build/FirebaseCore.xcframework"
      - framework: "Carthage/Build/FirebaseAnalytics.xcframework"
      - framework: "Carthage/Build/FirebaseCoreDiagnostics.xcframework"
      - framework: "Carthage/Build/FirebaseCoreInternal.xcframework"
      - framework: "Carthage/Build/GoogleAppMeasurement.xcframework"
      - framework: "Carthage/Build/GoogleAppMeasurementIdentitySupport.xcframework"
      - framework: "Carthage/Build/GoogleDataTransport.xcframework"
      - framework: "Carthage/Build/GoogleUtilities.xcframework"
    configFiles:
        Debug: Sources/Presentation/Configs/BuildConfigurations/Debug.xcconfig
        Staging: Sources/Presentation/Configs/BuildConfigurations/Staging.xcconfig
        Release: Sources/Presentation/Configs/BuildConfigurations/Release.xcconfig
    settings:
        INFOPLIST_FILE: Sources/Presentation/Resources/Info.plist
        SWIFT_VERSION: "5.0"
        SWIFT_OBJC_BRIDGING_HEADER: Sources/Presentation/Resources/MyApp-Bridging-Header.h
        CODE_SIGN_STYLE: "Manual"
        UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        UILaunchStoryboardName: LaunchScreen
        EXCLUDED_ARCHS[sdk=iphonesimulator*]: "arm64"
        VALIDATE_WORKSPACE: YES
    preBuildScripts:
        - name: SwiftGen
          script: |
            if which swiftgen >/dev/null; then
              swiftgen
            else
              echo "warning: SwiftGen not installed, download it from https://github.com/SwiftGen/SwiftGen"
            fi
    postCompileScripts:
        - name: Swiftlint
          script: |
            if which swiftlint >/dev/null; then
              swiftlint
            else
              echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
            fi
        - name: GoogleServiceInfo
          script: |
            PATH_TO_GOOGLE_PLISTS="${PROJECT_DIR}/Sources/Presentation/Configs/GoogleServices"
            case "${CONFIGURATION}" in
            "Debug" )
            cp -r "$PATH_TO_GOOGLE_PLISTS/GoogleService-Info-Debug.plist" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/GoogleService-Info.plist" ;;
            "Staging" )
            cp -r "$PATH_TO_GOOGLE_PLISTS/GoogleService-Info-Staging.plist" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/GoogleService-Info.plist" ;;
            "Release" )
            cp -r "$PATH_TO_GOOGLE_PLISTS/GoogleService-Info-Release.plist" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/GoogleService-Info.plist" ;;
            *)
            ;;
            esac
    postBuildScripts:
        - name: Crashlytics
          script: |
            "${PROJECT_DIR}/scripts/run"
          inputFiles:
            - $(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)
            - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
  MyAppTests:
    type: bundle.unit-test
    platform: iOS
    settings:
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/My App Debug.app/My App Debug
      LD_RUNPATH_SEARCH_PATHS: $(inherited) '@executable_path/Frameworks' '@loader_path/Frameworks' $(FRAMEWORK_SEARCH_PATHS)
      IPHONEOS_DEPLOYMENT_TARGET: 12.0
    sources: SourcesTests 
    dependencies:
      - target: MyApp  
schemes:
  My Project:
    build:
      targets:
        MyApp: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: MyAppTests
          parallelizable: false
          randomExecutionOrder: true
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Release