version: 2.1
orbs:
  slack: circleci/slack@4.12.0
aliases:
  - &restore_gem_cache
      name: Restore gem cache
      keys:
        - &gem-cache gem-cache-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        - gem-cache-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}
        - gem-cache-{{ .Environment.CACHE_VERSION }}
  - &save_gem_cache
      name: Save gem cache
      key: *gem-cache
      paths:
        - vendor/bundle
  - &gem_install
      name: Install Bundler and Gem
      command: scripts/circleci/ci-setup-ruby.sh
  - &config_mint
      name: Config Mint
      command: scripts/circleci/ci-setup-mint.sh
  - &restore_mint_cache
      name: Restore Mint cache
      keys:
        - &mint-cache mint-cache-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}-{{ checksum "Mintfile" }}
        - mint-cache-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}
        - mint-cache-{{ .Environment.CACHE_VERSION }}
  - &save_mint_cache
      name: Save Mint cache
      key: *mint-cache
      paths:
        - ./Mints
  - &mint_install_dependency
      name: Install dependency via Mint
      command: scripts/circleci/ci-install-mint.sh
  - &generate_resource
      name: Generate Resource
      command: scripts/circleci/ci-generate.sh
  - &restore_pod_cache
      name: Restore CocoaPods cache
      keys:
        - &pod-cache pod-cache-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}-{{ checksum "Podfile.lock" }}
        - pod-cache-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}
        - pod-cache-{{ .Environment.CACHE_VERSION }}
  - &save_pod_cache
      name: Save CocoaPods cache
      key: *pod-cache
      paths:
        - ./Pods
  - &install_pod
      name: Install cocoapods
      command: scripts/circleci/ci-install-pod.sh
jobs:
  build-and-test:
    macos:
      xcode: 14.0.1
    steps:
      - checkout
      - restore_cache: *restore_gem_cache
      - run: *gem_install
      - save_cache: *save_gem_cache
      - run: *config_mint
      - restore_cache: *restore_mint_cache
      - run: *mint_install_dependency
      - save_cache: *save_mint_cache
      - run: *generate_resource
      - restore_cache: *restore_pod_cache
      - run: *install_pod
      - save_cache: *save_pod_cache
      - run:
          name: Run Unit test
          command: make unittest
      - run:
          name: Create slather file
          command: scripts/circleci/ci-setup-slather.sh
      - run:
          name: Generate code coverage
          command: scripts/circleci/ci-code-coverage.sh
      - store_artifacts:
          path: fastlane/test_output
      - store_artifacts:
          path: xml_report
  deploy-apple:
    macos:
      xcode: 14.0.1
    steps:
      - checkout
      - restore_cache: *restore_gem_cache
      - run: *gem_install
      - save_cache: *save_gem_cache
      - run: *config_mint
      - restore_cache: *restore_mint_cache
      - run: *mint_install_dependency
      - save_cache: *save_mint_cache
      - run: *generate_resource
      - restore_cache: *restore_pod_cache
      - run: *install_pod
      - save_cache: *save_pod_cache
      - run:
          name: Create P8 API Key
          command: echo $APP_STORE_P8 | base64 --decode > AuthKey_6TF3P5J5QY.p8
      - run:
          name: Create ENV
          command: echo $ENV_CONTENT | base64 --decode > fastlane/.env.staging
      - run:
          name: Deploy Testflight
          no_output_timeout: 15m
          command: make testflight
      - store_artifacts:
          path: fastlane/build
workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
      - slack/on-hold:
          context: slack-secrets
          requires:
            - build-and-test
      - pause_workflow:
          requires:
            - build-and-test
            - slack/on-hold
          type: approval
      - deploy-apple:
          requires:
            - pause_workflow
