version: 2.1
orbs:
  slack: circleci/slack@4.12.0
aliases:
  - &restore_gem_cache
      name: Restore gem cache
      keys:
        - &gem-cache gem-cache-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        - gem-cache-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}
        - gem-cache-{{ .Environment.CACHE_VERSION }}
  - &save_gem_cache
      name: Save gem cache
      key: *gem-cache
      paths:
        - vendor/bundle
  - &gem_install
      name: Install Bundler and Gem
      command: |
        export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")
        gem install bundler:$BUNDLER_VERSION
        bundle config path vendor/bundle
        bundle install --without=documentation --jobs 4 --retry 3
  - &config_mint
      name: Config Mint
      command: scripts/mint/mint-setup.sh
  - &restore_mint_cache
      name: Restore Mint cache
      keys:
        - &mint-cache mint-cache-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}-{{ checksum "Mintfile" }}
        - mint-cache-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}
        - mint-cache-{{ .Environment.CACHE_VERSION }}
  - &save_mint_cache
      name: Save Mint cache
      key: *mint-cache
      paths:
        - ./Mints
  - &mint_install_dependency
      name: Install dependency via Mint
      command: HOMEBREW_NO_AUTO_UPDATE=1 make installMint
  - &generate_resource
      name: Generate Resource
      command: make generateResource
  - &restore_pod_cache
      name: Restore CocoaPods cache
      keys:
        - &pod-cache pod-cache-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}-{{ checksum "Podfile.lock" }}
        - pod-cache-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}
        - pod-cache-{{ .Environment.CACHE_VERSION }}
  - &save_pod_cache
      name: Save CocoaPods cache
      key: *pod-cache
      paths:
        - ./Pods
  - &install_pod
      name: Install cocoapods
      command: bundle exec pod install
jobs:
  build-and-test:
    macos:
      xcode: 14.0.1
    steps:
      - checkout
      - restore_cache: *restore_gem_cache
      - run: *gem_install
      - save_cache: *save_gem_cache
      - run: *config_mint
      - restore_cache: *restore_mint_cache
      - run: *mint_install_dependency
      - save_cache: *save_mint_cache
      - run: *generate_resource
      - restore_cache: *restore_pod_cache
      - run: *install_pod
      - save_cache: *save_pod_cache
      - run:
          name: Run Unit test
          command: bundle exec fastlane unittest --env debug
      - store_artifacts:
          path: fastlane/test_output
  deploy-apple:
    macos:
      xcode: 14.0.1
    steps:
      - checkout
      - restore_cache: *restore_gem_cache
      - run: *gem_install
      - save_cache: *save_gem_cache
      - run: *config_mint
      - restore_cache: *restore_mint_cache
      - run: *mint_install_dependency
      - save_cache: *save_mint_cache
      - run: *generate_resource
      - restore_cache: *restore_pod_cache
      - run: *install_pod
      - save_cache: *save_pod_cache
      - run:
          name: Create P8 API Key
          command: echo $APP_STORE_P8 | base64 --decode > AuthKey_6TF3P5J5QY.p8
      - run:
          name: Deploy Testflight
          no_output_timeout: 15m
          command: make upload_testflight_method_1
      - store_artifacts:
          path: fastlane/build
workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
      - slack/on-hold:
          context: slack-secrets
          requires:
            - build-and-test
      - pause_workflow:
          requires:
            - build-and-test
            - slack/on-hold
          type: approval
      - deploy-apple:
          requires:
            - pause_workflow
