version: 2.1
orbs:
  slack: circleci/slack@4.12.0
aliases:
  - &restore_gem_cache
      name: Restore gem cache
      keys:
        - &gem-cache gem-cache-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        - gem-cache-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}
        - gem-cache-{{ .Environment.CACHE_VERSION }}
  - &save_gem_cache
      name: Save gem cache
      key: *gem-cache
      paths:
        - vendor/bundle
  - &bundle_install
      name: Install Gems via Bundler
      command: |
        export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")
        gem install bundler:$BUNDLER_VERSION
  - &brew-install-mint
      name: Install Mint view Homebrew
      command: HOMEBREW_NO_AUTO_UPDATE=1 brew install mint
  - &restore_mint_cache
      name: Restore Mint cache
      keys:
        - &mint-cache mint-cache-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}-{{ checksum "Mintfile" }}
        - mint-cache-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}
        - mint-cache-{{ .Environment.CACHE_VERSION }}
  - &save_mint_cache
      name: Save Mint cache
      key: *mint-cache
      paths:
        - ./Mints
  - &mint-install-dependency
      name: Install dependency view Mint
      command: make installMint
  - &generate-resource
      name: Generate SwiftGen
      command: make generateResource
  - &restore_pod_cache
      name: Restore CocoaPods
      keys:
        - &pod-cache pod-cache-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}-{{ checksum "Podfile.lock" }}
        - pod-cache-{{ .Environment.CACHE_VERSION }}-{{ arch }}-{{ .Branch }}
        - pod-cache-{{ .Environment.CACHE_VERSION }}
  - &save_pod_cache:
      name: Save CocoaPods
      key: *pod-cache
      paths:
        - ./Pods
  - &install_pod
      name: Install cocoapods
      command: bundle exec pod install
jobs:
  build-and-test:
    macos:
      xcode: 14.0.1
    steps:
      - checkout
      - restore_cache: *restore_gem_cache
      - run: *bundle_install
      - save_cache: *save_gem_cache
      - run: *brew-install-mint
      - restore_cache: *restore_mint_cache
      - run: *mint-install-dependency
      - save_cache: *save_mint_cache
      - run: *generate-resource
      - restore_cache: *restore_pod_cache
      - run: *install_pod
      - run:
          name: Run Unit test
          command: bundle exec fastlane unittest --env debug
  deploy-apple:
    macos:
      xcode: 14.0.1
    steps:
      - checkout
      - restore_cache: *restore_gem_cache
      - run: *bundle_install
      - save_cache: *save_gem_cache
      - run: *brew-install-mint
      - restore_cache: *restore_mint_cache
      - run: *mint-install-dependency
      - save_cache: *save_mint_cache
      - run: *generate-resource
      - restore_cache: *restore_pod_cache
      - run: *install_pod
      - run:
          name: Setup Certificate
          command: make setupCertificate
      - run:
          name: Create P8 API Key
          command: echo $APP_STORE_P8 | base64 --decode > AuthKey_6TF3P5J5QY.p8
      - run:
          name: Deploy Testflight
          no_output_timeout: 15m
          command: make exportTestFlight
workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
      - slack/on-hold:
          context: slack-secrets
          requires:
            - build-and-test
      - pause_workflow:
          requires:
            - build-and-test
            - slack/on-hold
          type: approval
      - deploy-apple:
          requires:
            - pause_workflow