# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-and-test:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    macos:
      xcode: 14.0.1
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: Force Bundler Version
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: "Install"
          command: "make"
      - run:
          name: "Run Unit test"
          command: "bundle exec fastlane unittest --env debug"
  deploy-apple:
    macos:
      xcode: 14.0.1

    steps:
      - checkout
      - run:
          name: Force Bundler Version
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - add_ssh_keys:
          fingerprints:
            - "69:2d:fa:ad:1f:44:31:bb:04:01:34:06:62:e3:8f:72"
      - run:
          name: "Install"
          command: "make"
      - run:
          name: "Setup Certificate"
          command: "make setupCertificate"
      - run:
          name: "Deploy Testflight"
          command: "make exportTestFlight"

  setup-certificate:
    macos:
      xcode: 14.0.1

    steps:
      - checkout
      - run:
          name: Force Bundler Version
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run:
          name: "Fix bundle"
          command: "scripts/installDependencies.sh"
      - add_ssh_keys:
          fingerprints:
            - "69:2d:fa:ad:1f:44:31:bb:04:01:34:06:62:e3:8f:72"
      - run:
          name: "Install bundle"
          command: "make installBundle"
      - run:
          name: "Setup Certificate"
          command: "make setupCertificate"


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
  deploy-apple:
    jobs:
      - deploy-apple
  setup-certificate:
    jobs:
      - setup-certificate